### ISSUE TITLE
Optimize the dockerFile 

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium-docker-android#1]
- [x] Reduce the Android API's to latest 4 or 5 version
- [x] Eliminate Ant
- [x] Install Node (probably latest) directly
- [x] PATH setup [Environment variable's]
- [x] Reduce image Size (Currently it is > 3GB)
- [x] Expose all port's

**Comment by saikrishna321** [comment]
@SrinivasanTarget i don't see why we should expose ports ? Thoughts?

**Comment by SrinivasanTarget** [comment]
Yup not all but we need to expose appium server default port to access from outside. Now i find that we didn't exposed default port for vnc.
