### ISSUE TITLE
Device offline

### ISSUE THREAD

**Issue by Nesh911** [appium/appium-docker-android#105]
Hallo! When I try to connect a device, I fail, and the device changes the port. While I can not understand the reason, the version of the container with the earlier version works fine.

appium/appium:latest
root@928b6be7f7ae:~# adb connect 34.148.34.58:7437
failed to authenticate to 34.148.54.28:7437

root@928b6be7f7ae:~# adb devices
List of devices attached
34.148.54.28::7437	offline

**Comment by budtmo** [comment]
Hi @Nesh911 , 

it is probably because you have already connected that device with other adb. Could you check it agian?

**Comment by budtmo** [comment]
closed due to no response
