### ISSUE TITLE
How to run adb mobile shell commands with appium in docker?

### ISSUE THREAD

**Issue by aranvic** [appium/appium-docker-android#110]
Hi,
I've ran appium container in my project, but can not use mobile shell commands from code because it can not find adb. Can you help me with it?
The code looks like
            driver.executeScript("mobile: shell", ImmutableMap.of("command", "am broadcast -a io.appium.settings.locale --es lang " + currentLang + " --es country " + countryName));

**Comment by budtmo** [comment]
Hi @aranvic, 

could you share your test code maybe?
