### ISSUE TITLE
Unable to establish proper connection or run UI tests from the local host(MAC laptop) to docker container which runs appium server in it

### ISSUE THREAD

**Issue by adityabhargav** [appium/appium-docker-android#113]
getting issue as given below :--

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Original error: Failed to connect to /172.17.0.2:80
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'HYD-M-APATHIVADA.glu.com', ip: '10.7.4.149', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_181'
Driver info: driver.version: AndroidDriver

test code :- 

    @BeforeMethod
    public void setup() throws MalformedURLException {
        getPropValue = new dataHelper();
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("platformName", "Android");
        caps.setCapability("deviceName", getPropValue.getDeviceName());
        caps.setCapability("platformVersion", getPropValue.getPlatformName());
        caps.setCapability("udid", getPropValue.getUdid());
        caps.setCapability("appPackage", getPropValue.getAppPackage());
        caps.setCapability("appActivity", getPropValue.getAppActivity());
        caps.setCapability(MobileCapabilityType.APP, "/opt/ApiDemos.apk");
        caps.setCapability("unicodeKeyboard", "true");
        caps.setCapability("resetKeyboard", "true");
        caps.setCapability("noReset", "false");
        caps.setCapability(MobileCapabilityType.FULL_RESET, false);
        caps.setCapability("autoGrantPermission", true);
        driver = new AndroidDriver<MobileElement>(new URL("http://172.17.0.2:80/wd/hub"), caps);
}

I have followed the process as mention in link (https://github.com/appium/appium-docker-android) until 9th step ... after the 9th step ... since i've executed the UI test .... its thorwing the issue as mentioned above...

Kindly plz help...dire urgently....
Thanks in advance...

**Comment by budtmo** [comment]
Hi @adityabhargav ,

is it the correct ip of docker-machine? because it seems that it is not.

**Comment by adityabhargav** [comment]
Hi @budtmo ,

Im new to the docker ... kindly plz describe the steps to access the connection from host machine to appium server which is running in docker-machine's container in Mac-OsX

Thanks,
Aditya B

**Comment by adityabhargav** [comment]
> Hi @budtmo ,
> 
> Im new to the docker ... kindly plz describe in detail of steps to access the connection from host machine to appium server which is running in docker-machine's container in Mac-OsX
> 
> Thanks,
> Aditya B

**Comment by adityabhargav** [comment]
Hi @budtmo ,
Issue's solved by having an host of the particular dockerMachine in appium server

**Comment by 4runl0g** [comment]
@adityabhargav I am facing same issue. How did u resolve this? My appium grid url look this. Docker ip is something like 172.x.x.x
driver = new AndroidDriver<MobileElement>(new URL("http://localhost:4723/wd/hub"), caps);
