### ISSUE TITLE
No way to setup chrome driver version

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium-docker-android#115]
Hey,

Seems like there is no way to setup ChromeDriver version, the default version of the docker image is 1.7.0-beta appium,  but the version of ChromeDriver is 75.0.3770.90 which is too old. 

May I or someone else can do a quick PR?

**Comment by budtmo** [comment]
Hi @xuanzhaopeng , 

we pass the version on Appium through environment variable (dont rely on the version in Dockerfile). you can check using appium --version command. 

I will close the ticket and feel free to reopen it
