### ISSUE TITLE
docker-machine: command not found

### ISSUE THREAD

**Issue by v1nc3nt** [appium/appium-docker-android#124]
I'm new to docker.  I was interested in installing the appium-docker-android image since there was so much internet discussion about it. However, docker-machines no longer exist or the readme wasn't updated with instructions on how to use Docker Desktop to do the corresponding tasks.  Any suggestions

$ docker-machine
-bash: docker-machine: command not found

**Comment by budtmo** [comment]
Hi @v1nc3nt , 

docker-machine is the old system, you dont need docker-machine anymore
