### ISSUE TITLE
adb execution timeout error?

### ISSUE THREAD

**Issue by 123wuyu** [appium/appium-docker-android#127]
when i use this container to run appium, a adb error occurred？
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5037 -s HT76F0204864 shell settings delete global hidden_api_policy_pre_p_apps' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability

the following is docker log

[debug] [ADB] Running '/root/platform-tools/adb -P 5037 -s HT76F0204864 shell am force-stop com.ted.android'
[UiAutomator2] Unable to force stop app: Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5037 -s HT76F0204864 shell am force-stop com.ted.android' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability
[debug] [ADB] Running '/root/platform-tools/adb -P 5037 -s HT76F0204864 shell getprop ro.build.version.sdk'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1585923812207 (07:23:32 GMT-0700 (Pacific Daylight Time))
[debug] [W3C] Encountered internal error running command: Error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5037 -s HT76F0204864 shell getprop ro.build.version.sdk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability
[debug] [W3C]     at ADB.getApiLevel (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/adb-commands.js:115:13)
[HTTP] <-- POST /wd/hub/session 500 60146 ms - 1089

need help, ths

**Comment by budtmo** [comment]
close the issue as it might be fixed on the newest release. feel free to reopen the issue if the error still there
