### ISSUE TITLE
DockerFile Error?

### ISSUE THREAD

**Issue by jansenmelo** [appium/appium-docker-android#129]
Hello, i'm trying use dockerfile to change some configs and got this error:

 > node ./bin/install.js
 /usr/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:21
   androidHelpers.getJavaVersion(false).then(function tryInstall (version) {
                  ^
 TypeError: androidHelpers.getJavaVersion is not a function
     at doInstall (/usr/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:21:18)
     at Object.<anonymous> (/usr/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:63:3)
     at Module._compile (internal/modules/cjs/loader.js:1133:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
     at Module.load (internal/modules/cjs/loader.js:977:32)
     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
     at internal/main/run_main_module.js:18:47
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules/appium/node_modules/fsevents):
 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! appium-selendroid-driver@1.13.4 install: `node ./bin/install.js`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the appium-selendroid-driver@1.13.4 install script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2020-05-20T12_17_17_139Z-debug.log
 The command '/bin/sh -c curl -sL https://deb.nodesource.com/setup_12.x | bash &&     apt-get -qqy install nodejs &&     npm install -g appium@${APPIUM_VERSION} --unsafe-perm=true --allow-root &&     exit 0 &&     npm cache clean &&     apt-get remove --purge -y npm &&     apt-get autoremove --purge -y &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     apt-get clean' returned a non-zero code: 1

Anyone can help me?
I think this error is related to this line:
ARG APPIUM_VERSION=1.17.0-beta
ENV APPIUM_VERSION=$APPIUM_VERSION

npm install -g appium@${APPIUM_VERSION} --unsafe-perm=true --allow-root && \

**Comment by jansenmelo** [comment]
I think this problem still on this line:
  npm install -g appium@${APPIUM_VERSION} --unsafe-perm=true --allow-root && \

Maybe because the appium version used as 1.7.0-beta

**Comment by jansenmelo** [comment]
The solution has found.

npm cache clean --force && \

Inserted --force after cache clean, or remove npm, cache clean.

**Comment by jonathanMejiaL** [comment]
it is not working for me, any more update?
