### ISSUE TITLE
Enabling image comparison

### ISSUE THREAD

**Issue by arthuRHD** [appium/appium-docker-android#133]
Hi, will you implement `opencv4nodejs` inside your docker image ?

I've tested with this Dockerfile and it's running properly

```Dockerfile
FROM appium/appium
USER root

RUN apt update && apt dist-upgrade -y
RUN apt install -y --no-install-recommends \
        git cmake build-essential \
    && rm -rf /var/lib/apt/lists/*
RUN npm i -g opencv4nodejs --allow-root --unsafe-perm=true

CMD [ "appium", "--relaxed-security" ] # for adb shell

EXPOSE 4723
```

This is just an example since i'm a novice with Docker.

**Comment by budtmo** [comment]
Hi @arthuRHD , 

if you want to add sample project that use that package under ./examples then I think it wont hurt to add that package inside our docker image as the size is not big anyway. If we do, I think you need to add version number of that package.

**Comment by arthuRHD** [comment]
Sure i will, however i am quite busy now but it will be done soon

**Comment by budtmo** [comment]
close the issue due to no further response. feel free to reopen the issue.
