### ISSUE TITLE
ADB devices is not showing up

### ISSUE THREAD

**Issue by roopajoshyam** [appium/appium-docker-android#135]
Hi @SrinivasanTarget 

docker exec -it container-appium adb devices
List of devices attached

No device is listing here. I have done all the steps which is there in the documentation, still not able to see the list of devices.
Please help me to resolve this.

I m using macOS catalina.

**Comment by lubov-rykova** [comment]
hey, @roopajoshyam @SrinivasanTarget 

I cannot use adb as well, I'm using Big Sur
@roopajoshyam does it still not working for you?

**Comment by waleedather-10p** [comment]
Not seeing devices also, using windows.
Quick help will be appreciated.
