### ISSUE TITLE
Running '/root/platform-tools/adb -P 5037 reconnect offline'

### ISSUE THREAD

**Issue by ahmetdellall** [appium/appium-docker-android#139]
Good day, I have successfully completed the installation by following the installation steps.

<img width="536" alt="Screen Shot 2021-09-26 at 19 55 22" src="https://user-images.githubusercontent.com/3837391/134816854-ef1c8346-0f09-4916-bbf5-3c897a7fbac8.png">

When I say device list from container, devices come.

However, when I try to access the appium inspector from the web application, it sees the appium, but adb prints the following error.

<img width="848" alt="Screen Shot 2021-09-26 at 19 59 58" src="https://user-images.githubusercontent.com/3837391/134816978-8f04d4aa-b4eb-4ce6-892f-d30a53712404.png">

There is no method I haven't tried. I'm doing something wrong, can you help?

**Comment by wissemnano** [comment]
Hello @ahmetdellall , I'm facing the same issue in my company when testing the same Android devices, and I fix it with the same change in the docker image,
here is the link (docker-hub) for the image with the fix:  wissem1234/appium
=> I test it with many tests cases and devices and it fixes the issue, maybe this will fix your issue also.
could you please make some test with this image and put your result,

I want to contribute to this project and if it's possible to create a new image with a specific tag containing fixes.
if it's ok I'll create a merge request with updates.


Best Regards,
Wissem

**Comment by wissemnano** [comment]
> I hope this will fix the issue. This bug came up today but was working like a charm yesterday
i facing this issue , and this update fix it and i hope this will fix your issue to.

**Comment by arthuRHD** [comment]
This issue disappeared few days after my comment. It's in fact because 2 adbs were running. Maybe we can add some documentation about it.
