### ISSUE TITLE
Appium is failing to connect with Selenium Hub using Docker Compose

### ISSUE THREAD

**Issue by vsawant-CeX** [appium/appium-docker-android#149]
I have followed the documentation to use Docker-Compose file given at this [link](https://github.com/appium/appium-docker-android/blob/master/examples/docker-compose.yml) in our framework.

Also, I have used Docker desktop for mac to manage appium and selenium grid images. When I hit the command "docker-compose up", the appium server starts but it is failing to make a connection with the Selenium grid. Please find below logs, could you please help with the issue as we are trying to setup a grid node architecture.

Logs:= `android-app-automation-appium_android_device-1  | * daemon not running; starting now at tcp:5037
android-app-automation-appium_android_device-1  | * daemon started successfully
android-app-automation-appium_android_device-1  | Devices found: 0
android-app-automation-selenium_hub-1           | 2022-11-25 06:13:11,194 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
android-app-automation-selenium_hub-1           | 2022-11-25 06:13:11,212 INFO RPC interface 'supervisor' initialized
android-app-automation-selenium_hub-1           | 2022-11-25 06:13:11,212 CRIT Server 'unix_http_server' running without any HTTP authentication checking
android-app-automation-selenium_hub-1           | 2022-11-25 06:13:11,213 INFO supervisord started with pid 12
android-app-automation-selenium_hub-1           | 2022-11-25 06:13:12,221 INFO spawned: 'selenium-grid-hub' with pid 18
android-app-automation-selenium_hub-1           | Tracing is disabled
android-app-automation-selenium_hub-1           | 2022-11-25 06:13:12,304 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
android-app-automation-selenium_hub-1           | 06:13:15.934 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
android-app-automation-selenium_hub-1           | 06:13:15.974 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
android-app-automation-appium_android_device-1  | [Appium] Welcome to Appium v1.22.3
android-app-automation-appium_android_device-1  | [Appium] Non-default server args:
android-app-automation-appium_android_device-1  | [Appium]   logFile: /var/log/appium.log
android-app-automation-appium_android_device-1  | [Appium]   nodeconfig: /root/nodeconfig.json
android-app-automation-appium_android_device-1  | [debug] [Appium] Starting auto register thread for the grid. Will try to register every 5000 ms.
android-app-automation-appium_android_device-1  | [Appium] Appium REST http interface listener started on 0.0.0.0:4723
android-app-automation-selenium_hub-1           | 06:13:16.679 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.19.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.19.0.2:4443]
android-app-automation-selenium_hub-1           | 06:13:16.986 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.19.0.2:4442 and tcp://172.19.0.2:4443
android-app-automation-selenium_hub-1           | 06:13:17.089 INFO [UnboundZmqEventBus.<init>] - Sockets created
android-app-automation-selenium_hub-1           | 06:13:18.099 INFO [UnboundZmqEventBus.<init>] - Event bus ready
android-app-automation-appium_android_device-1  | [Appium] An attempt to register with the grid was unsuccessful: connect ECONNREFUSED 172.19.0.2:4444
android-app-automation-selenium_hub-1           | 06:13:22.358 INFO [Hub.execute] - Started Selenium Hub 4.6.0 (revision 79f1c02ae20): http://172.19.0.2:4444
android-app-automation-appium_android_device-1  | [debug] [Appium] Hub down or not responding: Request failed with status code 404
android-app-automation-appium_android_device-1  | [Appium] An attempt to register with the grid was unsuccessful: Request failed with status code 404
android-app-automation-appium_android_device-1  | [debug] [Appium] Hub down or not responding: Request failed with status code 404
android-app-automation-appium_android_device-1  | [Appium] An attempt to register with the grid was unsuccessful: Request failed with status code 404
android-app-automation-appium_android_device-1  | [debug] [Appium] Hub down or not responding: Request failed with status code 404
android-app-automation-appium_android_device-1  | [Appium] An attempt to register with the grid was unsuccessful: Request failed with status code 404
android-app-automation-appium_android_device-1  | [debug] [Appium] Hub down or not responding: Request failed with status code 404`

**Comment by budtmo** [comment]
based on the logs, it seems the device is not connected, please check if you share the usb to the docker container correctly. I will close the ticket for now as it is not a bug

**Comment by twiti7** [comment]
This docker-compose mentioned in post looks like outdated and not work for me too same error 404 Hub down ord not responding
