### ISSUE TITLE
Docker build on mac breaks due to JAVA_HOME error

### ISSUE THREAD

**Issue by OpHealer** [appium/appium-docker-android#159]
Docker build on mac will break and produce this error

`12 0.159 ERROR: JAVA_HOME is set to an invalid directory: /usr/bin/java
#12 0.159 
#12 0.159 Please set the JAVA_HOME variable in your environment to match the
#12 0.159 location of your Java installation.
#12 0.159 
#12 ERROR: executor failed running [/bin/sh -c mkdir -p ~/.android &&     touch ~/.android/repositories.cfg &&     echo y | sdkmanager "platform-tools" &&     echo y | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" &&     mv ~/.android .android &&     chown -R 1300:1301 .android]: exit code: 1`

I believe it is caused by setting JAVA_HOME to point to symlink target and not source, verified this by running ls -ll on /usr/lib/jvm

`#7 [ 4/15] RUN ls -ll /usr/lib/jvm
#7 sha256:d4488a56ef14b38ee2b0d99d1b62cf4f4c98dcd312d213312a38fd9e82050a48
#7 0.165 total 8
#7 0.165 lrwxrwxrwx 1 root root   21 Jan 20 09:07 java-1.11.0-openjdk-arm64 -> java-11-openjdk-arm64
#7 0.165 drwxr-xr-x 9 root root 4096 May  8 11:36 java-11-openjdk-arm64
#7 0.165 drwxr-xr-x 2 root root 4096 May  8 11:37 openjdk-11
#7 DONE 0.2s`

Changing JAVA_HOME in Appium/Dockerfile fixed it for me 
I used the symlink source:

Changed `ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-arm64` to `ENV JAVA_HOME="/usr/lib/jvm/java-1.11.0-openjdk-arm64"`

**Comment by budtmo** [comment]
Hi @OpHealer , 

Thank you for raising the issue. Could you create a PR from your solution to the repo? I will approve your PR and merge it.

**Comment by budtmo** [comment]
duplicated #162
