### ISSUE TITLE
Why different ports

### ISSUE THREAD

**Issue by vladburian1** [appium/appium-docker-android#167]
why in ReadMe we start appium exposing port 4723 but then connecting to it from code through port 32769
`docker run --privileged -d -p 4723:4723  -v /dev/bus/usb:/dev/bus/usb --name appium-container appium/appium`
`driver = new AndroidDriver<MobileElement>(new URL("http://192.168.99.100:32769/wd/hub"), caps);}`

**Comment by budtmo** [comment]
Hi @vladburian1 , 

Thank you for pointing out the typo. Could you correct it in the readme and create a PR? I will approve and merge it
