### ISSUE TITLE
Does this support all forms of architectures like X86, X86_64 and arm ?

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-docker-android#19]

**Comment by saikrishna321** [comment]
@vikramvi  nope

**Comment by vikramvi** [comment]
which all will it support ? nice to have this info in documentation please.

**Comment by irfanah** [comment]
@vikramvi agreed, will add them.

**Comment by vikramvi** [comment]
I'm trying out grid setup ( Serenity + Appium ) currently struck as Android Studio emulator ( ARM ) is super slow.

Was wondering if this image can support both ARM + X86 will be useful to community.

https://savvyapps.com/blog/state-android-emulators

**Comment by saikrishna321** [comment]
@vikramvi you could build it locally with your required architectures, we are supporting android-24 armeabi-v7a
