### ISSUE TITLE
docker build failing now after broken udev-rules url

### ISSUE THREAD

**Issue by notimewaste** [appium/appium-docker-android#22]
docker build failing on master with below error message 
```
https://raw.githubusercontent.com/M0Rf30/android-udev-rules/ubuntu/master/51-android.rules:
2017-02-04 16:39:12 ERROR 404: Not Found.
The command '/bin/sh -c mkdir /etc/udev/rules.d   && wget --no-verbose $UDEV_REMOTE_FILE -O /etc/udev/rules.d/51-android.rules' returned a non-zero code: 8
```

reason :  android-udev-rules remote file is removed at https://github.com/M0Rf30/android-udev-rules/commit/2010aef33573dfa098298d9b74f4d19df0ebb696

**Comment by argeas** [comment]
sam here... 404 for : https://raw.githubusercontent.com/M0Rf30/android-udev-rules/master/ubuntu/51-android.rules
