### ISSUE TITLE
Add Android_HOME and add to path

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium-docker-android#3]

**Comment by SrinivasanTarget** [comment]
Currently Android Home is set and added in path.Probably we can move it to refractor part.

**Comment by saikrishna321** [comment]
+1 it pulls from beevelop/android-nodejs:latest image, lets maintain within this dockerfile

**Comment by SrinivasanTarget** [comment]
Yup its updated here https://github.com/appium/appium-docker-android/issues/1

**Comment by saikrishna321** [comment]
https://github.com/appium/appium-docker-android/pull/10/files
