### ISSUE TITLE
docker login error in PR builder 

### ISSUE THREAD

**Issue by butomo1989** [appium/appium-docker-android#34]
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
The command "docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"" failed and exited with 1 during .

example: https://travis-ci.org/appium/appium-docker-android/builds/228003191?utm_source=github_status&utm_medium=notification

**Comment by SrinivasanTarget** [comment]
Credentials are perfectly fine but unfortunately it is security restriction of travis. Travis evaluates PR's only for those who have collaborator access to the repo. There are workarounds for the same proposed by @jlipps. We can look into it later.

**Comment by butomo1989** [comment]
fixed in https://github.com/appium/appium-docker-android/commit/877c79045dead7071add099a9580e047b855139c
