### ISSUE TITLE
Able to connect docker-appium with selenium grid

### ISSUE THREAD

**Issue by butomo1989** [appium/appium-docker-android#37]

**Comment by butomo1989** [comment]
if you want, you can also help to implement this one by using simple bash script @andrcuns

**Comment by andrcuns** [comment]
Would like to help :) But first, I'm looking in to one problem, it looks like there is a similar issue as mentioned [here](https://github.com/appium/appium/issues/5446), when running tests with real device using this container.

**Comment by butomo1989** [comment]
works and documented!
