### ISSUE TITLE
Feature request: tag docker images with appium version

### ISSUE THREAD

**Issue by serggl** [appium/appium-docker-android#44]
Hey,

can we tag published docker images with appium version?
Currently there is only `latest` tag available, but it does not tell you which appium version it has bundled.

Thank you

**Comment by SrinivasanTarget** [comment]
Ah makes sense. Will check.

**Comment by butomo1989** [comment]
We have already release tag 2.0-barcelona. If we make appium version as tag then the version of docker image and release tag will be decreased, e.g. 1.6.6-beta. Maybe we can put appium version in readme and release note.

**Comment by serggl** [comment]
actually `2.0-barcelona` is a bad tag name. `1.6.6-beta` is a proper one semantically. Just take a look how ruby team maintains their repository https://hub.docker.com/_/ruby/

**Comment by butomo1989** [comment]
@serggl The issue that I want to point out is not the name, but the version. :)
If we use appium version as tag then the version of docker-image and release tag will be decreased, e.g. from 1.1 to 2.0 and then become 1.6.6 which do not make sense in my opinion, unless we delete version 2.0. but I think @SrinivasanTarget can decide.

**Comment by serggl** [comment]
@butomo1989 I dont think that docker hub tags should exactly match this repo 'release tags'.
But
1. it should be clear from the dockerhub tags which version of appium you're pulling
2. dockerhub tags should be immutable (except of the `latest`). So once you decide to roll out appium upgrade - tag name should differ

but this is not what currently happening

**Comment by diemol** [comment]
Maybe you can follow the same pattern as in docker-selenium https://github.com/SeleniumHQ/docker-selenium/wiki/Tagging-Convention
E.g.: Selenium version 3.4.0, docker-selenium tag -> 3.4.0-chromium

In my opinion, it should be easy to understand for anyone which version of Appium is being used. This will facilitate a lot bug reporting and related issues.
