### ISSUE TITLE
Pass version of SDK, Android build tools and appium through travis

### ISSUE THREAD

**Issue by butomo1989** [appium/appium-docker-android#49]
Pass version of SDK, Android build tools and Appium through travis and use those as build-args to avoid a commit that only contains version changes of those dependencies.

**Comment by andrcuns** [comment]
Wouldn't You still have to commit to .travis.yml either way? :)

**Comment by butomo1989** [comment]
No, because the environment variables option is under settings in travis CI. @andrcuns but we need to create release tag for that so the image is pushed, otherwise it will build the new image without pushing it to docker hub.

**Comment by andrcuns** [comment]
After I wrote the comment, I remembered that one can configure env variables in travis CI :)
