### ISSUE TITLE
READ ME needs why section

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-docker-android#51]
@SrinivasanTarget Today watched your talk https://www.youtube.com/watch?v=jGW6ycW_tTQ&list=PLRdSclUtJDYXFVU37NEqh4KkT78BLqjcG&index=7, quite informative.

I feel it'll be nice to mention one liner in README; that this helps in quick setup of environment for Appium + Android automation. Also please check and clarify query in comment on video

Thanks,
Vikram

**Comment by SrinivasanTarget** [comment]
@vikramvi I didn't get your question there. Can you explain the question or problem here?

**Comment by SrinivasanTarget** [comment]
> I feel it'll be nice to mention one liner in README; that this helps in quick setup of environment for Appium + Android automation. Also please check and clarify query in comment on video

Would you like to raise a PR here?

**Comment by vikramvi** [comment]
sure @SrinivasanTarget I will raise PR this week.
