### ISSUE TITLE
Cannot run adb command

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium-docker-android#57]
docker-machine --version
> 0.11.0
# Create docker
docker-machine create --driver vmwarefusion appium-test-machine

# Get appium/appium
```
docker@appium-test-machine:~$ docker run --privileged -d -p 4723:4723  -v /dev/bus/usb:/dev/bus/usb --name container-appium appium/appium
Unable to find image 'appium/appium:latest' locally
latest: Pulling from appium/appium
bd97b43c27e3: Pull complete 
6960dc1aba18: Pull complete 
2b61829b0db5: Pull complete 
1f88dc826b14: Pull complete 
73b3859b1e43: Pull complete 
6c8edd7bef99: Pull complete 
92bcf1dd83d3: Pull complete 
fd1899cf6bd3: Pull complete 
52a115f9495b: Pull complete 
3ec5d10ba228: Pull complete 
d537468e7c38: Pull complete 
4ef145e4c267: Pull complete 
a6b1588c78cf: Pull complete 
Digest: sha256:4dfb8854f1df95d3090ba8b7fb3eb4e07ee06878f2c8ec0e5778de3fe7f426a6
Status: Downloaded newer image for appium/appium:latest
c30d10172588807e3c28587a5e770d5d9aaa4b01160173369e695424d0ecd859
```

```
docker@appium-test-machine:~$ docker exec -it container-appium bash "adb"
/root/platform-tools/adb: /root/platform-tools/adb: cannot execute binary file
```

Could u have a look why I cannot execute adb?  Is it because I use VMFusion?

**Comment by xuanzhaopeng** [comment]
PS docker-machine 0.12.0 have some pb about ssh.

I just rollback to 0.11.0

**Comment by xuanzhaopeng** [comment]
When I do 
```
docker exec -it container-appium bash entry_point.sh
```
It will show xvbf failed to start


When I do 
```
docker exec -it container-appium bash generate_config.sh
```
It show : generate_config.sh: line 75: $node_config_json: ambiguous redirect

**Comment by red-avtovo** [comment]
> It will show xvbf failed to start
Because there is no image in docker hub with this fix #55 

> generate_config.sh: line 75: $node_config_json: ambiguous redirect
it's because dicker image already lost it's environment variables

**Comment by xuanzhaopeng** [comment]
I just use virtual box instead of vmfusion on macOS,  following the steps in ReadMe, i get same problem.

**Comment by SrinivasanTarget** [comment]
Seems like a path issue @xuanzhaopeng Will look into this.

**Comment by xuanzhaopeng** [comment]
ok , here the command works:

```
docker exec -it container-appium adb devices
```

The command below doesn't work
```
docker exec -it container-appium bash "adb devices"
```

**Comment by red-avtovo** [comment]
@xuanzhaopeng just make a PR =)
