### ISSUE TITLE
Cannot figure out why it is unable to auto connect android device by air 

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium-docker-android#58]
Hey,

> docker-machine version 0.11.0

Following command doesn't work:
```
docker run -d -t -i -e REMOTE_ADB=True -e ANDROID_DEVICES=172.16.101.218:5555 -e CONNECT_TO_GRID=True -e APPIUM_HOST="127.0.0.1" -e APPIUM_PORT=4723 -e SELENIUM_HOST="172.16.101.221" -e SELENIUM_PORT=4444 -p 4723:4723 --name container-appium appium/appium
```

Also I check the log of container by following command, I cannot see any logs print out by generate_config.sh
```
docker logs container-appium
```

But if I do following will works:
```
docker run -d -t -i -e CONNECT_TO_GRID=True -e APPIUM_HOST="127.0.0.1" -e APPIUM_PORT=4723 -e SELENIUM_HOST="172.16.101.221" -e SELENIUM_PORT=4444 -p 4723:4723 --name container-appium appium/appium
docker exec -it container-appium adb connect 172.16.101.218:5555
```

**Comment by xuanzhaopeng** [comment]
Could you point out how could see the log which print out by generate_config.sh when/after container created?

I use docker &events & docker logs, I cannot find any output from generate_config.sh, I only could see the log of Appium

**Comment by red-avtovo** [comment]
There is no proper way, how to get the logs, but you can see the appium and shell scripts outputs by attaching to container anytime by typing:
`docker attach container-appium`

> But if I do following will works:
docker run -d -t -i -e CONNECT_TO_GRID=True -e APPIUM_HOST="127.0.0.1" -e APPIUM_PORT=4723 -e SELENIUM_HOST="172.16.101.221" -e SELENIUM_PORT=4444 -p 4723:4723 --name container-appium appium/appium
docker exec -it container-appium adb connect 172.16.101.218:5555

That wouldn't work as soon as Appium config was already generated once on startup and it wouldn't regenerate it after you connected a device to it

**Comment by xuanzhaopeng** [comment]
The reason is : https://github.com/appium/appium-docker-android/issues/60
