### ISSUE TITLE
The command of retrieve device by adb devices is incorrect

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium-docker-android#60]
Source code : https://github.com/appium/appium-docker-android/blob/master/Appium/generate_config.sh#L44

```
devices=($(adb devices | grep -oP "\K([^ ]+)(?=\sdevice(\W|$))"))
```

The reason is when I create a container, there is no "device",  it will be "unauthorized"

should be 
```
devices=($(adb devices | grep -oP "\K([^ ]+)(?=\s(device|unauthorized)(\W|$))"))
```

**Comment by SrinivasanTarget** [comment]
@xuanzhaopeng Would you like to raise a PR?

**Comment by red-avtovo** [comment]
I'm not sure, that we should "see" unauthorized devices as soon as we are trying to generate node config from props, that we are requesting from devices, like 
`os_version="$(adb -s $name shell getprop ro.build.version.release | tr -d '\r')"`
This command will fail and we will get a broken config, which will affect tests evaluation
