### ISSUE TITLE
Running with docker only, not docker-machine

### ISSUE THREAD

**Issue by TuHuynhVan** [appium/appium-docker-android#62]
Thank you for the image! @SrinivasanTarget 
I'm going to apply it after seeing your talk in SeleniumConf on Youtube.

I got a concern. Can I just only use ```docker``` instead of ```docker-machine```

Thank you!

**Comment by andrcuns** [comment]
You will not be able to access USB unfortunately since [https://github.com/moby/hyperkit](HyperKit) which is used for Docker for Mac doesn't expose USB, well at least it didn't when I last tried it.

**Comment by SrinivasanTarget** [comment]
> Can I just only use docker instead of docker-machine 

@TuHuynhVan Thanks for watching. Yes if you use ubuntu machine. AFAIK, `docker-machine` is mandatory for mac as @andrcuns said.

**Comment by TuHuynhVan** [comment]
Thanks @andrcuns and @SrinivasanTarget for the clarification.
