### ISSUE TITLE
Adb server freeze when run test in parallel in Docker for Mac + USB 2.0 controller

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium-docker-android#66]
I just start this topic when you start one docker-machine with multiple appium-docker-android containers , and run test in parallel

I found adb server will freeze just after several run when u start test in multiple containers. However I cannot figure out the reason... 

I'd like to know whether you guys maybe also found this problem. 

PS: when u run test only in ONE container, it works perfect.

**Comment by butomo1989** [comment]
Hi @xuanzhaopeng ,

why do you need to have multiple containers? I think you can register multiple devices in one single container as long as devices are connected to the same machine.

**Comment by xuanzhaopeng** [comment]
Hey @butomo1989 , just back from selenium conference, I will try your solution today

**Comment by xuanzhaopeng** [comment]
Hey @butomo1989 @red-avtovo I figure it out based on : https://stackoverflow.com/questions/29563183/connecting-to-a-usb-android-device-in-a-docker-container-via-adb

The adb server instance should have different port within multiple containers

PS: @butomo1989  the reason why I use multiple containers because I want to create scalable selenium-node, and to make the log could be readable instead of mixed all sessions log into one

**Comment by xuanzhaopeng** [comment]
I think we could keep this issue here, and for others who want to use appium-docker @saikrishna321

**Comment by butomo1989** [comment]
In my opinion we should move this issue to for example FAQ or something else in the readme/documentation if we won’t to work on this issue.

**Comment by saikrishna321** [comment]
@butomo1989 we should Document this

**Comment by butomo1989** [comment]
Could you maybe help to move it to readme @xuanzhaopeng ? I think you can explain it in a better way.

**Comment by butomo1989** [comment]
I will close this ticket. I think It should be fixed through explanations of issue #72 and #76 for running one appium server for one container. Please feel free to reopen it if needed.
