### ISSUE TITLE
I am trying to run my android automation locally then getting given error bellow.

### ISSUE THREAD

**Issue by fabiohsl** [appium/appium-docker-android#77]
Failed to open TCP connection to 172.17.0.2:4723

Seems that I cannot see my appium-docker locally. Is there some further configuration that I am missing?

**Comment by butomo1989** [comment]
Hi @fabiohsl , 

It might be because of proxy thing?

**Comment by fabiohsl** [comment]
Hi @butomo1989 thanks for the answer! I’ve solved the issue configuring a second network card as bridge mode. Then for proxy should I use the docker manager right ?

**Comment by butomo1989** [comment]
Hi @fabiohsl , 

yes and as far as I know you can pass through environment variable. 
I will close this issue. Please feel free to reopen it if needed.

**Comment by fabiohsl** [comment]
Thank you @butomo1989 :)
