### ISSUE TITLE
Question, Connect Each Device to a Separate Container

### ISSUE THREAD

**Issue by moradkh** [appium/appium-docker-android#80]
Hi, 
I have connect 3 devices to the host. 
But unfortunately, i didn't success to find the devices when i ssh to the container, just find the first device. 

May it related to the command:
$ docker run -d -p 4723:4723 --device /dev/bus/usb/XXX/YYY:/dev/bus/usb/XXX/YYY -v ~/.android:/root/.android --name device1 appium/appium

What is the XXX/YYY ? can anyone help me ? 
How i can recognize the local USB to share it with the docker ?

Here is my usb connected devices to the virtual box:
<img width="648" alt="screen shot 2018-07-01 at 12 10 32 pm" src="https://user-images.githubusercontent.com/1182988/42132813-e29a0f9e-7d27-11e8-9182-821fb9198ab1.png">

Thanks,

**Comment by butomo1989** [comment]
Hi @moradkh , 

does it work on your local machine (without docker-appium)? if yes, then it might be because of device driver that you need to install inside container or because the other 2 devices are already connected with your local adb and the other one is connected with container adb.

**Comment by moradkh** [comment]
Hi @butomo1989 , 

Thank you for your response, It works fine for 3 devices, using the same use path.

**Comment by shridharkabbur** [comment]
Hi, If i run multiple containers one for each device, how to get dev/usb/bus path for each device?
