### ISSUE TITLE
Device Not Shown

### ISSUE THREAD

**Issue by anshu1987** [appium/appium-docker-android#81]
I tried to execute command : docker exec -it container-appium adb devices and it doesn't show up any devices 
docker@appium-test-machine:~$ docker exec -it container-appium adb devices
List of devices attached

It only shows List of devices attached and nothing else.
Can you please help how can it would be available.?

**Comment by fabiohsl** [comment]
Hej @anshu1987 we will need more information. Just double check some bullets before we go ahead. In case that needed to use VirtualBox Have you done 

`vboxmanage modifyvm appium-test --usb on --usbehci on`

Are you able to see your device as shown below?

https://raw.githubusercontent.com/appium/appium-docker-android/master/images/virtualbox.png

Once you are able to see your device on your VirtualBox. Double check whether you've accepted the given pop-up below:

https://raw.githubusercontent.com/appium/appium-docker-android/master/images/authorization.png

For the this one above I don't think so, once in case that you get some trouble related to that "auth" pop-up you would be able to see your device after your "docker exec -it container-appium adb devices" like "adb device unauthorized". Let me know if you are able to see your device on virtualBox.

**Comment by anshu1987** [comment]
Hi @fabiohsl  , 

Yes I executed this command vboxmanage modifyvm appium-test --usb on --usbehci on,attached is screen shot for the same:
<img width="1270" alt="screen shot 2018-07-13 at 12 09 33 pm" src="https://user-images.githubusercontent.com/4101167/42676467-f5489c74-8695-11e8-8893-8e99dc12a37d.png">

Regarding pop up , i see the pop up whenever i connect my device to machine and i choose always allow option.
If I do "adb devices" , on my machine it list the device but if i do adb devices on the machine it says adb is not found.

Any command to map device with docker.

**Comment by fabiohsl** [comment]
Ok. @anshu1987 do one thing, remove your device from the USB. Reboot your docker env, then connect your device again. The thing is once it gets remembered on your local machine it won't get "mapped" to your docker env. Let me know whether those steps fix it.

**Comment by fabiohsl** [comment]
@anshu1987 let me know whether those works to you.

**Comment by anshu1987** [comment]
Hi @fabiohsl  : sorry for late revert , i tried the step mentioned by you but not able to succeed.
Doing step adb-kill server saying adb is not found.
I am doing everything on newly created machine via VM Virtual Box Manager , please find below the screen shot of the same. I have not installed adb on that machine do i required to install that?
My assumption is when I am building the docker image it should be automatically there?

<img width="775" alt="screen shot 2018-07-14 at 10 11 02 pm" src="https://user-images.githubusercontent.com/4101167/42726487-de9f8d84-87b2-11e8-92b9-a09e825bdb55.png">

**Comment by anshu1987** [comment]
@fabiohsl  : If you are successful with the solution then is there a way we can connect via any medium like skype or gtalk , so that we can discussed directly.?After successful launch can share my findings over here.

**Comment by fabiohsl** [comment]
Hej @anshu1987 I've added you on skype.

**Comment by anshu1987** [comment]
Hi fabiohsl,
I din't get any Skype request. My Skype ID is: anshu-khandelwal
Or you can share yours I'll send request.

**Comment by anshu1987** [comment]
Hi @fabiohsl  : Were you able to add me?

**Comment by butomo1989** [comment]
close the issue due to inactivity. Please feel free to reopen it.
