### ISSUE TITLE
issue after restarting the container

### ISSUE THREAD

**Issue by kiranask** [appium/appium-docker-android#85]
Once after restart the docker image - appium-test-machine, 
And perform adb devices, `docker exec -it container-appium adb devices`
I am getting.
Error response from daemon: Container 79c6625c09eb91fcf98521f20fbec3f1bd4d679ab82a9728c0d0e8d2e3ca8a39 is not running
How to fix this ?

**Comment by butomo1989** [comment]
Hi @kiranask , 

yes, I think it is a bug, because we havent tested it. but as a workaround, you can kill the container and bring a new one for now (dont forget to share .android folder to avoid authorization page).

**Comment by kiranask** [comment]
After removing the container and creating another it worked for me. But it's not good practice to kill and start the container for every error.

**Comment by megolee** [comment]
Try to add rm -rf /tmp/.X99-lock after this line https://github.com/appium/appium-docker-android/blob/master/Appium/entry_point.sh#L29

And build appium yourself like this https://github.com/appium/appium-docker-android#how-to-build

This solve my problem.

**Comment by budtmo** [comment]
Hi @megolee , 

do you want to be part of this project as contributor by sending PR for this issue? it would be great.

**Comment by megolee** [comment]
Hi @budtmo ,

I have already send a PR. Please review it and contact me if there is any problem.

**Comment by budtmo** [comment]
It should be fixed in version [1.11.1-p2](https://github.com/appium/appium-docker-android/releases/tag/1.11.1-p2).
