### ISSUE TITLE
Unable to copy .apk file inside container-appium

### ISSUE THREAD

**Issue by kiranask** [appium/appium-docker-android#86]
I am able to perform,
`docker cp /Users/loacl-macosx-path-to-apk/app-debug.apk container-appium:/opt`
Above command doesnot give me any error response, but if navigate to 
```
opt$ 
docker@appium-test-machine:/opt$ ls -l
total 20
-rwxr-xr-x    1 root     root            51 Jul 19 18:33 bootlocal.sh
-rwxr-xr-x    1 root     root          2383 Dec 10  2017 bootscript.sh
-rwxr-xr-x    1 root     root           286 Jan  5  2017 bootsync.sh
-rwxr-xr-x    1 root     root           137 Jan  5  2017 shutdown.sh
-rw-rw-r--    1 root     staff           31 Jul 19 18:33 tcemirror
```

I am not finding my apk file there. Is this expected ?

**Comment by butomo1989** [comment]
Hi @kiranask ,

Do you use the correct container name? I think you should use volume sharing instead of copying it manually.

**Comment by butomo1989** [comment]
Closed because there is no response. Please feel free to reopen it if needed

**Comment by kiranask** [comment]
Yes I am using same container name
