### ISSUE TITLE
Error start session: Appium 1.9.0 + docker container

### ISSUE THREAD

**Issue by aikuznetsov** [appium/appium-docker-android#87]
The problem

Hi! I wanna perform my test in parallel at some devices with docker. I launched docker container, which sees only 1 necessary device. But when I try to create appium driver I receive "[GET http://localhost:8200/wd/hub/status] with no body" error.

Environment

Appium version Appium v1.9.1
Desktop OS/version used to run Appium: 16.04.1-Ubuntu
Node.js version: 6.4.1
Mobile platform/version under test: Android 7.0
Real device or emulator/simulator: Real device
Docker container: docker pull appium/appium (with updated appium and node.js)
https://hub.docker.com/r/appium/appium/
Link to Appium logs

https://gist.github.com/aikuznetsov/50abddf6dfc0ea9a04fdb5a704c66f05

Code To Reproduce Issue [ Good To Have ]

Start docker container: docker run --rm -d --device /dev/bus/usb/003/075:/dev/bus/usb/003/075 -v ~/.android:/root/.android --name device1 appium/appium

Attempt to create driver:
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName", deviceID);
capabilities.setCapability("model", "SM_A310F");
capabilities.setCapability("udid", deviceID);
capabilities.setCapability("automationName", "uiautomator2");
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("platformVersion", "7.0");
capabilities.setCapability("newCommandTimeout", "0");
capabilities.setCapability("appPackage", HOTSPOTSHIELD);
capabilities.setCapability("appActivity", HSS_MAIN_ACTIVITY);

**Comment by butomo1989** [comment]
Hi @aikuznetsov ,

which Appium version do you use? 1.9.0 or 1.9.1? because the title and the description is not match. but I think it should be 1.9.0 because we still support version 1.9.0 for the current Docker Image. 

from the log, I am not sure if it is related to the docker container itself. could it be a bug in Appium? @SrinivasanTarget @saikrishna321

**Comment by butomo1989** [comment]
[Docker image](https://github.com/appium/appium-docker-android/releases/tag/1.9.1-p0) that contains 1.9.1 is released.

**Comment by saikrishna321** [comment]
@aikuznetsov what happens when u run the below command inside the container

```
adb -s 31007f50f410b2f3 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner
```

**Comment by butomo1989** [comment]
Updated with Appium version 1.10.0, so I will close this issue. Feel free to reopen it
