### ISSUE TITLE
Run on the Windows OS

### ISSUE THREAD

**Issue by Pramodnp28** [appium/appium-docker-android#88]
Hello, 
Am completely new to the dockers when am trying to run dockers compose with the following yml file 
`version: '2'

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub
    ports:
      - 4444:4444

  # Appium Docker Android  
  appium_android_device:
    image: appium/appium
    depends_on:
      - selenium_hub
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      # Enable it for msite testing
      #- BROWSER_NAME=chrome`

### ERROR
ERROR: for appiumrequired_appium_android_device_1  Cannot create container for service appium_android_device: b'Mount denied:\nThe source path "\\\\dev\\\\bus\\\\usb:/dev/bus/usb"\nis not a valid Windows path'

ERROR: for appium_android_device  Cannot create container for service appium_android_device: b'Mount denied:\nThe source path "\\\\dev\\\\bus\\\\usb:/dev/bus/usb"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.

### Complete log
PS C:\Users\DELL\Desktop\Appium Required> docker-compose up -d
Starting appiumrequired_selenium_hub_1 ... done
Creating appiumrequired_appium_android_device_1 ... error

ERROR: for appiumrequired_appium_android_device_1  Cannot create container for service appium_android_device: b'Mount denied:\nThe source path "\\\\dev\\\\bus\\\\usb:/dev/bus/usb"\nis not a valid Windows path'

ERROR: for appium_android_device  Cannot create container for service appium_android_device: b'Mount denied:\nThe source path "\\\\dev\\\\bus\\\\usb:/dev/bus/usb"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.

**Comment by butomo1989** [comment]
It is because you use windows OS. you need to ssh your docker-machine first because there is no such path in windows OS. The [readme](https://github.com/appium/appium-docker-android/blob/master/README.md) shows how to do it in Mac using docker-machine command, you can try for Windows and let us know how it works. Could you also add it in the readme if you are able to use it?

**Comment by cai-git** [comment]
is the windows os ok? my system is windows.

**Comment by budtmo** [comment]
duplicated #140
