### ISSUE TITLE
Unable to connect to 2 real devices

### ISSUE THREAD

**Issue by quyennt44** [appium/appium-docker-android#93]
Hi,
Could you have a look.

I'm using your docker-compose file to start appium docker [https://github.com/appium/appium-docker-android/blob/master/examples/docker-compose.yml](https://github.com/appium/appium-docker-android/blob/master/examples/docker-compose.yml).

I connect 2 real devices and I start the docker-compose file like this:
`docker-compose up -d --scale appium_android_device=2`
When I check the selenium grid server, one container receives 2 devices while the other receives no device.
When I run test, one container is crashed with this message:
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Android bootstrap socket crashed: Error: This socket has been ended by the other party`

Please help me.

Thanks.

**Comment by butomo1989** [comment]
Hi @quyennt44 , 

by default all devices will be recognized in one single container. if you want to have one device for each container, please read the readme. 
I will close this issue. Please feel free to open it if needed.

**Comment by quyennt44** [comment]
@butomo1989 Thanks for your reply.
Could I ask you one more question.
If I want to run test parallel on 2 real devices, then can I use one single container with 2 devices, or should I use 2 containers, each device on a container?

Thank you.

**Comment by butomo1989** [comment]
you can use both ways.

**Comment by quyennt44** [comment]
@butomo1989 Could you give me an advice on my error log, I can not find what is the problem.
Thank you!

This is the docker-compose content:
`# Note: It requires docker-compose 1.6.0+
#
# Usage: docker-compose up -d
version: '2'

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub
    ports:
      - 4444:4444

  # Appium Docker Android  
  appium_android_device:
    image: appium/appium
    depends_on:
      - selenium_hub
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      # Enable it for msite testing
      #- BROWSER_NAME=chrome`

This is the selenium grid console:
![selection_015](https://user-images.githubusercontent.com/43987470/50826469-4bc45880-136e-11e9-84fb-eeeb902c76a0.png)
![selection_016](https://user-images.githubusercontent.com/43987470/50826478-5121a300-136e-11e9-9248-511dc19468a3.png)

This is the source code to connect to selenium grid and appium:
`package vn.teko.appium.cucumber.test.runners.base;

import java.io.IOException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Parameters;

import io.appium.java_client.android.AndroidDriver;
import vn.teko.appium.common.FileReaderManager;
import vn.teko.appium.common.ThreadLocalDriver;

public class BaseTest {

    public WebDriverWait wait;    

    @SuppressWarnings("rawtypes")
	@BeforeMethod
    @Parameters({"deviceName", "platformVersion", "udid"})
    public void setup (String deviceName, String platformVersion, String udid) throws IOException {
        System.out.println("TestNG Before");

        //Unlock the device if it is locked.
//        final Runtime rt = Runtime.getRuntime();
//        rt.exec("adb shell input keyevent 224");

        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("deviceName", deviceName);
        caps.setCapability("platformVersion", platformVersion);
        caps.setCapability("udid", udid);
        caps.setCapability("platformName", "Android");
        caps.setCapability("appPackage", "org.wordpress.android");
        caps.setCapability("appActivity","org.wordpress.android.ui.WPLaunchActivity");
        caps.setCapability("noReset","false");
        
        ThreadLocalDriver.setTLDriver(new AndroidDriver (new URL("http://localhost:4444/wd/hub"),caps));
        
//        caps.setCapability("platformName", FileReaderManager.getInstance().getConfigReader().getPlatformName());
//        caps.setCapability("appPackage", FileReaderManager.getInstance().getConfigReader().getAppPackage());
//        caps.setCapability("appActivity",FileReaderManager.getInstance().getConfigReader().getAppActivity());
//        caps.setCapability("noReset",FileReaderManager.getInstance().getConfigReader().getNoReset());
//        caps.setCapability("automationName","UiAutomator2");
        
//        ThreadLocalDriver.setTLDriver(new AndroidDriver (new URL(FileReaderManager.getInstance().getConfigReader().getGridServerUrl()),caps));
        wait = new WebDriverWait(ThreadLocalDriver.getTLDriver(), 30);   
    }

    @AfterMethod
    public synchronized void teardown(){    	
    	try {
    		ThreadLocalDriver.getTLDriver().closeApp();
    		ThreadLocalDriver.getTLDriver().quit();
    	}catch(Exception ex){
    		ex.printStackTrace();
    	}
    }

}
`

This is testNG file used to run test:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
 
<suite name="Wordpress-Android-Test-Suite" parallel="tests" thread-count="2">
 
   <test name="Test-SamsungJ3" parallel="classes" thread-count="1">
        <parameter name="deviceName" value="SamsungJ3" />
        <parameter name="platformVersion" value="5.1.1" />
        <parameter name="udid" value="42006fd2cc118400" />
        <classes>
            <class name="vn.teko.appium.cucumber.test.runners.signup.RunSignupFeature" />
        </classes>
    </test>
 
   <test name="Test-AndroidPad" parallel="classes" thread-count="1">
        <parameter name="deviceName" value="AndroidPad" />
        <parameter name="platformVersion" value="5.1.1" />
        <parameter name="udid" value="5200e90dfa179400" />
        <classes>
            <class name="vn.teko.appium.cucumber.test.runners.login.RunLoginFeature" />
        </classes>
    </test> 
</suite>

`

Everything looks ok but when I run the test, only one device can run. This is the error log:
[https://github.com/quyennt44/logs/blob/master/appiumLog.txt](https://github.com/quyennt44/logs/blob/master/appiumLog.txt)

**Comment by quyennt44** [comment]
I set the appium property "noReset = true" then the error seems fixed. But I don't know what the root reason is.
