### ISSUE TITLE
Bootstrap socket crash

### ISSUE THREAD

**Issue by yahyakara** [appium/appium-docker-android#95]
Hi Budi, 
Firstly i want to thanks you for amazing documents, I registered multiple devices on one container and
When I run tests, i get error message:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Android bootstrap socket crashed: Error: This socket has been ended by the other party

Please help me.how Can i solve this issue

Thanks a lot

**Comment by budtmo** [comment]
Hi @yahyakara ,

could you try it using Appium on local machine? because I don't think, the issue related to this project. if it gives the same error, then you need to create an issue to [Appium project](https://github.com/appium/appium/issues)

**Comment by budtmo** [comment]
close due to no response
