### ISSUE TITLE
Failed to establish a new connection Error 

### ISSUE THREAD

**Issue by kiranask** [appium/appium-docker-android#96]
I am getting   MaxRetryError: HTTPConnectionPool(host='192.168.99.100', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106cdea90>: Failed to establish a new connection: [Errno 61] Connection refused',)) 
While running the my automation suite.

**Comment by budtmo** [comment]
Hi @kiranask ,

could you try it using Appium on local machine? because I don't think, the issue related to this project. if it gives the same error, then you need to create an issue to [Appium project](https://github.com/appium/appium/issues)

**Comment by budtmo** [comment]
close due to no response
