### ISSUE TITLE
Give option to install Appium with Espresso Driver

### ISSUE THREAD

**Issue by mohit-sentieo** [appium/appium-docker-android#99]

**Comment by mohit-sentieo** [comment]
It would be very useful to be able to run Appium with Espresso driver since that method has significant advantages over the UIAutomator. 
https://github.com/appium/appium-espresso-driver

**Comment by budtmo** [comment]
Hi @mohit-sentieo , 

I do not use espresso driver yet but I think you just need to choose espresso and pass it through capabilities and it will download the driver automatically. is it true? @SrinivasanTarget

**Comment by saikrishna321** [comment]
@mohit-sentieo Just pass the automationName as espresso and appium will start a espresso session instead of UIA2
